## Chapter 1, 2

In [1]:
# Main imports

# Secondary imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# Local imports

In [3]:
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 20
np.set_printoptions(precision=4, suppress=True)


In [4]:
!python

^C


In [5]:
print("Hello World!")

Hello World!


In [6]:
a = 5
a

5

In [7]:
data = [np.random.standard_normal() for i in range(7)]
data
# Prettier print than using `print()` function

[0.3419597038896397,
 -0.14376820927105727,
 -0.987323738990567,
 -1.4548773373584702,
 -0.35231251583403905,
 -0.14540514869168378,
 -0.1552536560472769]

In [8]:
print(data)

[0.3419597038896397, -0.14376820927105727, -0.987323738990567, -1.4548773373584702, -0.35231251583403905, -0.14540514869168378, -0.1552536560472769]


In [9]:
# Tab Completion
an_apple = 27
an_example = 42

In [10]:
b = [1, 2, 3]
b.sort()

In [11]:
b

[1, 2, 3]

In [12]:
import datetime
datetime.MAXYEAR

9999

In [13]:
# Introspection
b?

In [14]:
print?

In [15]:
def intrpospector_fn(a, b):
    """
    A function to discuss how to add introspectors
    :param a: useless
    :param b: useless
    :return: doesn't return anything
    """

In [16]:
intrpospector_fn?

In [17]:
a = [1, 2, 3]

In [18]:
b

[1, 2, 3]

In [19]:
a.append(4)

In [20]:
b

[1, 2, 3]

In [21]:
a = 5

In [23]:
isinstance(a, int)

True

In [24]:
isinstance(a, (str, bool))

False

In [25]:
isinstance(a, (int, str, bool))

True

In [26]:
a = "foo"

In [27]:
a.isalnum()

True

In [28]:
a.isdigit()

False

In [29]:
getattr(a, "split")

<function str.split(sep=None, maxsplit=-1)>

Duck typing
If it walks like a duck and quacks like a duck -> then it is a duck

In [30]:
#Duck typing
#If it walks like a duck and quacks like a duck -> then it is a duck
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError:
        return False

In [31]:
isiterable("rlmvglkmvg")

True

In [32]:
isiterable([])

True

In [33]:
isiterable(5)

False

In [34]:
a = [1, 2, 3]
b = a
c = [1, 2, 3]

In [35]:
a is b

True

In [36]:
a is c

False

In [37]:
a == c

True

In [38]:
assert a is not c

In [39]:
a = 64561651
a ** 6

72418206844053502254282716836430322923584457401

In [40]:
3 // 2

1

In [41]:
3 / 2

1.5

In [43]:
a = 'qwe'
b = "eqw"

In [44]:
a = """
rlkmrklmrl;g
lkgmrklmg
"""
a

'\nrlkmrklmrl;g\nlkgmrklmg\n'

In [45]:
b = '''
ffflr
rl;mgl;trg
;rl;rl;
'''
b

'\nffflr\nrl;mgl;trg\n;rl;rl;\n'

In [47]:
b.count('\n')

4

In [48]:
b[0] = 'r'

TypeError: 'str' object does not support item assignment

In [1]:
a = "this is a string"
b = a.replace('is', 'was')

In [2]:
a

'this is a string'

In [3]:
b

'thwas was a string'

In [4]:
a = 5.6

In [5]:
s = str(a)

In [6]:
print(s)

5.6


In [7]:
s = "python"
list(s)

['p', 'y', 't', 'h', 'o', 'n']

In [8]:
s[:3]

'pyt'

In [10]:
s = "12\\34"
print(s)

12\34


In [11]:
s = r"this\kdfnlkgn\fl;gml;fg\g"
print(s)

this\kdfnlkgn\fl;gml;fg\g


In [12]:
s + s

'this\\kdfnlkgn\\fl;gml;fg\\gthis\\kdfnlkgn\\fl;gml;fg\\g'

In [13]:
template = "{0:.2f} {1:s} are worth US${2:d}"

In [16]:
template.format(88.46, "Argentine Pesos", 1)

'88.46 Argentine Pesos are worth US$1'

In [18]:
amount = 10
rate = 88.46
currency = "pesos"
result = f"{amount} {currency} is worth US${amount/rate}"

In [19]:
result

'10 pesos is worth US$0.11304544426859599'

In [20]:
result = f"{amount} {currency} is worth US${amount/rate: .2f}"
result

'10 pesos is worth US$ 0.11'

In [1]:
val = "اليونيكود اللي مظبطني ظبيط"

In [2]:
val

'اليونيكود اللي مظبطني ظبيط'

In [3]:
a = "lol"
b = a
c = "lol"

a is b

True

In [5]:
a == c

True

In [7]:
b is c
# This is strange actually! this mean that pthon makes us of strings
# immutability so that it create them once and whoever needs them just
# point to the existing ones since they will never change


True

In [ ]:
x = 5
if x < 5:
    x*=2
elif x == 0:
    pass
else:
    x /= 2

In [1]:
list(range(0, 20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [2]:
seq = [1, 2, 3, 4]

for i in range(len(seq)):
    print(f"element {i}:{seq[i]}")

element 0:1
element 1:2
element 2:3
element 3:4


## Chapter 3: Built-in DS

In [ ]:
"""
Chapter 3: Built-in DS, functions and files
"""

In [3]:
tup = (1, 2, 3)

In [4]:
tup

(1, 2, 3)

In [5]:
tup = 1,2,3

In [6]:
tup

(1, 2, 3)

In [7]:
tuple([4, 5, 6])

(4, 5, 6)

In [8]:
tup = tuple('dklnlkdndf')

In [9]:
tup

('d', 'k', 'l', 'n', 'l', 'k', 'd', 'n', 'd', 'f')

In [11]:
tuple?

In [13]:
str?

In [14]:
(1, 2, 'dfdf') + (["Gh", 54], 7)

(1, 2, 'dfdf', ['Gh', 54], 7)

In [15]:
(1, 2, 'dfdf') + (["Gh", 54], 7) * 2

(1, 2, 'dfdf', ['Gh', 54], 7, ['Gh', 54], 7)

In [16]:
a = 4
b = 6

In [17]:
a, b = b, a

In [18]:
a

6

In [20]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
for a, b, c in seq:
    print(f"a = {a}, b = {b}, c = {c}")

a = 1, b = 2, c = 3
a = 4, b = 5, c = 6
a = 7, b = 8, c = 9


In [21]:
a, *b = seq[0]

In [24]:
b
# llliiiissssssttttt

[2, 3]

In [23]:
a

1

In [25]:
a?

In [26]:
a = 1,2,5,8,7,4,2,15,7,5

In [27]:
a.count(2)

2

In [1]:
gen = range(10)

In [2]:
gen

range(0, 10)

In [3]:
# Materialize an iterator or generator by list
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
a = list(gen)

In [5]:
a.append("klgnfg")

In [6]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'klgnfg']

In [7]:
a.insert(2, "After 1 before 2")
# Or just only in the 2nd index and push whatever there forward

In [8]:
a

[0, 1, 'After 1 before 2', 2, 3, 4, 5, 6, 7, 8, 9, 'klgnfg']

In [9]:
# insert is computationally expensive compared with append

In [10]:
# Insert XXXXXX Pop
a.pop(2)

'After 1 before 2'

In [11]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'klgnfg']

In [12]:
# Remove by value not index
a.remove('klgnfg')

In [13]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
if(a):
   print("Exist")

Exist


In [15]:
b = None
if(not b):
    print("Not exist")

Not exist


In [16]:
0 in a

True

In [17]:
51 not in a

True

In [18]:
(1, 2, 3) + (8, 9)

(1, 2, 3, 8, 9)

In [19]:
[1, 4, 9] + [65, 79, 988]

[1, 4, 9, 65, 79, 988]

In [20]:
x = [1, None, 3]

In [21]:
x.extend([4, 5, 6])

In [22]:
x

[1, None, 3, 4, 5, 6]

In [23]:
a = [7, 2, 8, 2, 0, 78]
a.sort()

In [24]:
a

[0, 2, 2, 7, 8, 78]

In [1]:
b = ["sd", "f, 545", "Dfdf"]
b.sort(key=len)

In [2]:
b

['sd', 'Dfdf', 'f, 545']

In [6]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]

In [7]:
seq[1] = [5, 5]

In [8]:
seq

[7, [5, 5], 3, 7, 5, 6, 0, 1]

In [9]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]


In [10]:
seq[1:] = [5, 5]

In [11]:
seq

[7, 5, 5]

In [12]:
d1 = {"a": "some value", "b": [1, 2, 3, 4]}

In [13]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [14]:
d1[7] = "an integer"

In [15]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [16]:
d1['b']

[1, 2, 3, 4]

In [17]:
'b' in d1

True

In [18]:
d1[5] = "some value"

In [19]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [20]:
d1["dummy"] = "another value"
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 5: 'some value',
 'dummy': 'another value'}

In [21]:
del d1["dummy"]

In [22]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [24]:
d1.pop(5)

'some value'

In [25]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [26]:
list(d1.items())

[('a', 'some value'), ('b', [1, 2, 3, 4]), (7, 'an integer')]

In [27]:
list(d1.keys())

['a', 'b', 7]

In [30]:
list(d1.values())

['some value', [1, 2, 3, 4], 'an integer']

In [31]:
d1.update({'b': 'foo', "c": 54})

In [32]:
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 54}

In [2]:
tuples = zip(range(10), reversed(range(10)))
mapping = dict(tuples)
mapping

{0: 9, 1: 8, 2: 7, 3: 6, 4: 5, 5: 4, 6: 3, 7: 2, 8: 1, 9: 0}

In [1]:
words = ["apple", "bat", "bar", "atom", "book"]
by_letter = {}
for word in words:
    by_letter.setdefault(word[0], []).append(word)

In [2]:
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [3]:
from collections import defaultdict
by_letter = defaultdict(list)

for word in words:
    by_letter[word[0]].append(word)

In [4]:
hash("sd")

-7498495525349040318

In [6]:
hash((1, 2))

-3550055125485641917

In [7]:
hash([1, 4])

TypeError: unhashable type: 'list'

In [8]:
hash((1, 2, 3, []))

TypeError: unhashable type: 'list'

In [9]:
d = {}
d[tuple([1, 2])] = 5
d

{(1, 2): 5}

In [10]:
sd = {1,2,1,2,4,5,8,7,6,2,2,3,4,5,6}
sd

{1, 2, 3, 4, 5, 6, 7, 8}

In [11]:
a = {1, 2, 3, 4, 5}
b = {6, 7, 8, 9, 10, 11, 12}

In [13]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

In [14]:
a.intersection(b)

set()

In [15]:
a.difference(b)

{1, 2, 3, 4, 5}

In [16]:
a|b

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

In [18]:
a & b

set()

In [19]:
a - b

{1, 2, 3, 4, 5}

In [20]:
a &= b

In [21]:
a

set()

In [22]:
a.add([1, 2, 3])

TypeError: unhashable type: 'list'

In [24]:
a.add(tuple([1, 2, 3]))

In [25]:
a

{(1, 2, 3)}

In [1]:
strings = ["a", "as", "bat", "car", "dove", "python"]
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [2]:
unique_lengths = {len(x) for x in strings}

In [5]:
unique_lengths

{1, 2, 3, 4, 6}

In [6]:
set(map(len, strings))

{1, 2, 3, 4, 6}

In [7]:
loc_mapping = {value: index for index, value in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [8]:
all_data = [["John", "Emily", "Michael", "Mary","Steven"], ["Maria", "Juan", "Javier", "Natalia", "Pilar"]]

In [9]:
name_of_interest = []

for names in all_data:
    enough_as = [name for name in names if name.count("a") >= 2]
    name_of_interest.extend(enough_as)

In [10]:
name_of_interest

['Maria', 'Natalia']

In [11]:
result = [name for names in all_data for name in names if name.count("a") >= 2]
result

['Maria', 'Natalia']

In [3]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]

In [4]:
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
"""
You can have arbitrarily many levels of nesting, though if you have more than two or three levels of nesting, you should probably start to question whether this makes sense from a code readability standpoint.
"""

'\nYou can have arbitrarily many levels of nesting, though if you have more than two or three levels of nesting, you should probably start to question whether this makes sense from a code readability standpoint.\n'

In [8]:
[{x for x in tup} for tup in some_tuples]

[{1, 2, 3}, {4, 5, 6}, {7, 8, 9}]

In [9]:
{[x for x in tup] for tup in some_tuples}

TypeError: unhashable type: 'list'

In [10]:
def my_function2(x, y, z=1.5):
    if z > 1:
        return x * y / z
    else:
        return x * y * z

In [11]:
my_function2(1, 2, 3)

0.6666666666666666

In [12]:
my_function2(1, 2, z=3)


0.6666666666666666

In [13]:
my_function2(1, 2)


1.3333333333333333

In [14]:
"""
The main restriction on function arguments is that the keyword arguments must follow the positional arguments (if any). You can specify keyword arguments in any order. This frees you from having to remember the order in which the function arguments were specified. You need to remember only what their names are.
"""

'\nThe main restriction on function arguments is that the keyword arguments must follow the positional arguments (if any). You can specify keyword arguments in any order. This frees you from having to remember the order in which the function arguments were specified. You need to remember only what their names are.\n'

In [15]:
a = []
def func():
    for i in range(5):
        a.append(i)

a

[]

In [16]:
func()
a

[0, 1, 2, 3, 4]

In [17]:
func(); func()
a

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [25]:
"""
Assigning variables outside of the function’s scope is possible, but those
variables must be declared explicitly using either the global or nonlocal
keywords:
"""
a = 5
def bind_a_variable():
    global a
    # nonlocal a
    a = []

bind_a_variable()

In [26]:
a

[]

In [2]:
import re

def clean_strings(strings):
    results = []
    for string in strings:
        string = string.strip()
        string = re.sub("[!#?]", "", string)
        string = string.title()
        results.append(string)

    return results
clean_strings([" Alabama ", "Georgia!", "Georgia",
"georgia", "FlOrIda", "south carolina##", "West virginia?"])

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

In [3]:
def remove_panctuation(value):
    return re.sub("[!#?]", "", value)

clean_ops = [str.strip, remove_panctuation, str.title]

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for function in clean_ops:
            value = function(value)
        result.append(value)
    return result

clean_strings([" Alabama ", "Georgia!", "Georgia",
"georgia", "FlOrIda", "south carolina##", "West virginia?"], clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

In [6]:
states = [" Alabama ", "Georgia!", "Georgia",
"georgia", "FlOrIda", "south carolina##", "West virginia?"]

for x in map(remove_panctuation, states):
    print(x)

 Alabama 
Georgia
Georgia
georgia
FlOrIda
south carolina
West virginia


In [7]:
def short_function(x):
    return x * 2

equiv_anonymous = lambda x: x * 2

In [8]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

ints = [4, 0, 1, 5, 6]
apply_to_list(ints, lambda x: x * 2)

[8, 0, 2, 10, 12]

In [11]:
strings = ["foo", "fkgnfgkl", 'ffgfg', 'a', 'b']

strings.sort(key=lambda x: len(x))

In [12]:
strings

['a', 'b', 'foo', 'ffgfg', 'fkgnfgkl']

### Generators

In [1]:
d = {"a": 1, "b": 2, "c": 3}
for key in d:
    print(key, d[key])

a 1
b 2
c 3


In [2]:
# First step that python do
dict_iterator = iter(d)

dict_iterator

In [3]:
min(dict_iterator)

'a'

In [4]:
sum(dict_iterator)

0

In [5]:
nums = [1, 2, 3]
it = iter(nums)     # ده iterator
print(next(it))     # 1
print(next(it))     # 2
print(next(it))     # 3


1
2
3


In [6]:
# Generators are special case of iterators

In [7]:
def squares(n=10):
    print(f"Generating squares from 1 to {n ** 2}")
    for i in range(1, n + 1):
         yield i ** 2

In [8]:
gen = squares()

In [9]:
for x in gen:
    print(x, end = " ")

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

In [10]:
# Generator expressions

gen = (x ** 2 for x in range(100))
gen

<generator object <genexpr> at 0x000002A308888EE0>

In [11]:
sum(gen)

328350

In [12]:
# Generator expressions can be used instead of list comprehensions as function arguments in some cases:

sum(x ** 2 for x in range(100))

328350

In [13]:
dict((i, i ** 2) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [6]:
import itertools
first_letter = lambda x: x[0]
names = ["Alan", "Adam", "Wes", "Will", "Albert", "Steven"]
for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names))

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


In [14]:
def attempt_float(x):
    try:
        return float(x)
    except ValueError:
        return x

print(attempt_float(1.5), end=" ")
print(type(attempt_float("1.5")), end=" ")
print(type(attempt_float("1...5")))

1.5 <class 'float'> <class 'str'>


In [15]:
print((attempt_float((1, 2))))

TypeError: float() argument must be a string or a real number, not 'tuple'

In [16]:
def attempt_float(x):
    try:
        return float(x)
    except (ValueError, TypeError):
        return x

print((attempt_float((1, 2))))

(1, 2)


In [6]:
f = open("README.md")
try:
    f.write("Data Science Labs")
except (TypeError, ValueError):
    print("Failed")
else:
    print("Succeeded")
finally:
    f.close()

Failed


In [1]:
path = r"C:\Users\20106\PycharmProjects\Data-Science\scrapped_websites\page_string.txt"

In [8]:
f = open(path, encoding="utf-8")

In [ ]:
for line in f:
    print(line)

In [ ]:
lines = [x.rstrip() for ]

In [10]:
# with: automatically closes the files
with open(path, encoding='utf-8') as f:
    lines = [x.rstrip() for x in f]

lines[:10]

['',
 '',
 '<!doctype html>',
 '',
 '<!--[if gt IE 8]><!-->',
 '',
 '<html class="no-js" lang="ar">',
 '',
 '<!--<![endif]-->',
 '']

In [4]:
f1 = open(path, mode='rb')

f1.read(1)

b'\r'

In [5]:
f1.tell()

1

In [6]:
import sys
sys.getdefaultencoding()

'utf-8'

In [13]:
f1.seek(3)
f1.read(1)

b'<'

In [14]:
f1.seek(1)
f1.read(3)

b'\r\n<'

In [15]:
f1.close()

In [17]:
# UTF-8 character can be represented in 1-4 bytes (variable)
# So if you open a file txt (default) reader it will read number of bytes between x and 4x
# But if you open a file binary reader, it will read only x bytes which are written in your file

In [19]:
with open(path, mode='rb') as f:
    data = f.read(10)

data

b'\r\r\n<!docty'

In [22]:
with open(path, mode='r', encoding='utf-8') as f:
    data = f.read(10)

data

'\n\n<!doctyp'

In [9]:
with open(path, mode="rb") as f:
    data = f.read(15)

data

b'\r\r\n<!doctype ht'

In [10]:
data.decode("utf-8")

'\r\r\n<!doctype ht'

In [12]:
data[:11].decode("utf-8")

'\r\r\n<!doctyp'

In [3]:
path = r"C:\Users\20106\PycharmProjects\Data-Science\Datasets\IMDB Dataset.csv"
sink_path = r"C:\Users\20106\PycharmProjects\Data-Science\Datasets\IMDB_binary.csv"

In [6]:
with open(path, encoding="utf-8") as source:
    with open(sink_path, "x", encoding="iso-8859-1") as sink:
        sink.write(source.read())

UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 466570: ordinal not in range(256)

In [ ]:
"""Beware using seek when opening files in any mode other than binary. If the
file position falls in the middle of the bytes defining a Unicode character, then
subsequent reads will result in an error:
In [269]: f = open(path, encoding="""

## Chapter 4: NumPy Basics: Arrays and Vectorized Computation

In [1]:
"""مكونات نامباي:
* ndarray: السرعة في العلميات
* math functions: عمليات سرعة على الأرراي من غير لووبس
* للكتابة القراءة من والى الديسك
* الجبر الخطي؛ توليد الأرقام العشوائية؛ قدرات فوريرية ترانسفورمية
 * واجهة تربط النامباي بال c,c++, fortran"""

'مكونات نامباي:\n* ndarray: السرعة في العلميات\n* math functions: عمليات سرعة على الأرراي من غير لووبس\n* للكتابة القراءة من والى الديسك\n* الجبر الخطي؛ توليد الأرقام العشوائية؛ قدرات فوريرية ترانسفورمية\n * واجهة تربط النامباي بال c,c++, fortran'

In [2]:
import numpy as np

In [1]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%timeit my_arr2 = my_arr * 2

1.85 ms ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [3]:
%timeit myist2 = [x * 2 for x in my_list]

154 ms ± 3.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

In [10]:
# Batch ops in numpy
data = np.array([[0,1,2],[3,4,5]])
data

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
data * 10

array([[ 0, 10, 20],
       [30, 40, 50]])

In [12]:
data + data

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('int32')

In [15]:
type(data)

numpy.ndarray

In [16]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1
# Easiest way => from a any sequence data

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
seq2 = (1, 2, 5)
arr2 = np.array(seq2)
arr2

array([1, 2, 5])

In [18]:
seq3 = {1, 2, 4} # Doesn't work
arr3 = np.array(seq3)
arr3

array({1, 2, 4}, dtype=object)

In [19]:
arr3[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [20]:
seq4 = [[1, 2, 3], [4, 5, 6]]
arr4 = np.array(seq4)
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr1.ndim, arr2.ndim, arr3.ndim, arr4.ndim

(1, 1, 0, 2)

In [22]:
arr1.shape, arr2.shape, arr3.shape, arr4.shape

((5,), (3,), (), (2, 3))

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.empty(10)
"""It’s not safe to assume that numpy.empty will return an array of all
zeros. This function returns uninitialized memory and thus may contain
nonzero “garbage” values. You should use this function only if you intend
to populate the new array with data."""

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [28]:
np.empty((2, 2, 2))

array([[[5.43472210e-322, 1.38629608e-314],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 1.37350250e-320],
        [0.00000000e+000, 1.94693963e-308]]])

In [30]:
np.arange(15).dtype

dtype('int32')

In [31]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
arr2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

In [32]:
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [1]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [2]:
# casting
float_arr = arr.astype(np.float64)
float_arr, float_arr.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

In [4]:
arr = np.array([3.7, 1.2, .02, 9.1, -4.5])
arr

array([ 3.7 ,  1.2 ,  0.02,  9.1 , -4.5 ])

In [5]:
arr.astype(np.int32)

array([ 3,  1,  0,  9, -4])

In [7]:
numeric_strings = np.array(["1.25", "-9.6", "42"])
numeric_strings.astype(float) * 2

array([  2.5, -19.2,  84. ])

In [3]:
int_array = np.arange(10)

In [5]:
calibers = np.array([.22, .270, .357, .380, .44, .50])
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
zero_uint32 = np.zeros(8, dtype="u4")
zero_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [7]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [9]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr ** -5

array([[1.00000000e+00, 3.12500000e-02, 4.11522634e-03],
       [9.76562500e-04, 3.20000000e-04, 1.28600823e-04]])

In [11]:
arr2 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
arr2 > arr

array([[False, False, False],
       [False, False, False]])

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5]

5

In [15]:
arr[5:8]

array([5, 6, 7])

In [16]:
arr[5:8] = 6
arr

array([0, 1, 2, 3, 4, 6, 6, 6, 8, 9])

In [17]:
arr[5:8] = [7]

In [18]:
arr

array([0, 1, 2, 3, 4, 7, 7, 7, 8, 9])

In [22]:
arr_slice = arr[5:8]

In [23]:
arr_slice[:] = 2

In [24]:
arr

array([0, 1, 2, 3, 4, 2, 2, 2, 8, 9])

In [25]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0]

array([1, 2, 3])

In [26]:
arr2d[0][1]

2

In [27]:
arr2d[0, 1]

2

In [28]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],
[10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d.shape

(2, 2, 3)

In [30]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr3d[0].shape

(2, 3)

In [33]:
arr3d[0, 1].shape

(3,)

In [34]:
arr3d[0, 1]

array([4, 5, 6])

In [35]:
o = arr3d.copy()
arr3d[0] = 1
arr3d

array([[[ 1,  1,  1],
        [ 1,  1,  1]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d = o
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [38]:
x[0]

array([7, 8, 9])

In [39]:
arr

array([0, 1, 2, 3, 4, 2, 2, 2, 8, 9])

In [40]:
arr[1:6]

array([1, 2, 3, 4, 2])

In [41]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr2d[0:2][1:]

array([[4, 5, 6]])

In [45]:
arr2d[0:2, 1:]

array([[2, 3],
       [5, 6]])